version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - fms_net

networks:
  fms_net:
    external:
      name: fms_net
